#!/usr/bin/env python3
"""Generate evidence indexes and validate repository Markdown."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

SECTIONS = {
    "adr": (
        "Architecture decisions",
        "Accepted design decisions, constraints, and rejected alternatives.",
    ),
    "audits": (
        "Validation audits",
        "Regression, live-system, release, and requirement-to-evidence audits.",
    ),
    "experiments": (
        "Experiment records",
        "Bounded research experiments with their protocol, evidence, and outcome.",
    ),
    "performance": (
        "Performance reports",
        "Measured latency, throughput, utilization, and scaling evidence.",
    ),
    "plans": (
        "Implementation plans",
        "Historical implementation plans retained for decision context.",
    ),
}

IGNORED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "dist",
}

INLINE_LINK = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
REFERENCE_LINK = re.compile(r"^\s*\[[^\]]+\]:\s+(\S+)", re.MULTILINE)
FENCE = re.compile(r"^\s*(?:```|~~~)")


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    raise ValueError(f"{path.relative_to(ROOT)} has no level-one heading")


def render_index(section: str) -> str:
    title, description = SECTIONS[section]
    directory = DOCS / section
    entries = sorted(
        (
            path
            for path in directory.glob("*.md")
            if path.name.casefold() != "readme.md"
        ),
        key=lambda path: path.name.casefold(),
    )
    lines = [
        f"# {title}",
        "",
        description,
        "",
        "This index is generated by `scripts/docs.py`. Edit the source document's",
        "first heading, then regenerate the index.",
        "",
        f"Documents: {len(entries)}",
        "",
        "## Index",
        "",
    ]
    for path in entries:
        lines.append(f"- [{first_heading(path)}]({path.name})")
    lines.append("")
    return "\n".join(lines)


def markdown_files() -> list[Path]:
    return sorted(
        (
            path
            for path in ROOT.rglob("*.md")
            if not any(part in IGNORED_PARTS for part in path.relative_to(ROOT).parts)
        ),
        key=lambda path: path.relative_to(ROOT).as_posix().casefold(),
    )


def local_target(raw_target: str) -> str | None:
    target = raw_target.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    if " " in target:
        target = target.split(" ", 1)[0]
    lowered = target.casefold()
    if (
        not target
        or target.startswith("#")
        or lowered.startswith(("http://", "https://", "mailto:", "tel:"))
    ):
        return None
    return unquote(target.split("#", 1)[0])


def validate_markdown(path: Path) -> list[str]:
    relative = path.relative_to(ROOT)
    text = path.read_text(encoding="utf-8")
    errors: list[str] = []
    prose_lines: list[str] = []
    inside_fence = False
    for line in text.splitlines():
        if FENCE.match(line):
            inside_fence = not inside_fence
            continue
        if not inside_fence:
            prose_lines.append(line)
    prose = "\n".join(prose_lines)

    if not any(line.startswith("# ") for line in text.splitlines()):
        errors.append(f"{relative}: missing level-one heading")

    if sum(bool(FENCE.match(line)) for line in text.splitlines()) % 2:
        errors.append(f"{relative}: unbalanced Markdown code fence")

    targets = INLINE_LINK.findall(prose) + REFERENCE_LINK.findall(prose)
    for raw_target in targets:
        target = local_target(raw_target)
        if target is None:
            continue
        resolved = (
            ROOT / target.lstrip("/")
            if target.startswith("/")
            else path.parent / target
        ).resolve()
        try:
            resolved.relative_to(ROOT)
        except ValueError:
            errors.append(f"{relative}: link escapes repository: {raw_target}")
            continue
        if not resolved.exists():
            errors.append(f"{relative}: broken link: {raw_target}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate evidence indexes and validate Markdown."
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite generated evidence indexes before validation",
    )
    args = parser.parse_args()

    errors: list[str] = []
    for section in SECTIONS:
        index_path = DOCS / section / "README.md"
        expected = render_index(section)
        if args.write:
            index_path.write_text(expected, encoding="utf-8")
        elif not index_path.exists():
            errors.append(f"{index_path.relative_to(ROOT)}: generated index is missing")
        elif index_path.read_text(encoding="utf-8") != expected:
            errors.append(
                f"{index_path.relative_to(ROOT)}: generated index is stale; "
                "run scripts/docs.py --write"
            )

    for path in markdown_files():
        errors.extend(validate_markdown(path))

    if errors:
        for error in errors:
            print(f"docs: {error}", file=sys.stderr)
        return 1

    print(
        f"docs: OK ({len(markdown_files())} Markdown files, "
        f"{len(SECTIONS)} generated indexes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
